<a href="https://colab.research.google.com/github/priyanka260604/first_gitrepo/blob/main/breastcancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('/content/breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.shape

(569, 32)

In [ ]:
df.drop(columns=['id'],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

**TRAIN TEST SPLIT**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

**Scaling or Standardisation**

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

**Label Encoding**

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

**Numpy Array to PyTorch tensors**

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [ ]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([-1.3468,  0.6016, -1.3412, -1.1056,  0.5624, -0.8118, -0.8637, -0.9448,
          0.7482,  0.4506,  0.1058,  3.0184, -0.0398, -0.3423,  2.5432, -0.4942,
         -0.5938, -0.4895,  1.1960,  0.3295, -1.1305,  0.9270, -1.1592, -0.9357,
          0.8933, -0.8533, -1.0129, -1.1814, -0.0656, -0.0683],
        dtype=torch.float64),
 tensor(0))

In [ ]:
train_loader=DataLoader(train_dataset,batch_size=16,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=16,shuffle=False)

**Defining the model**

In [ ]:
''' class NN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
     '''
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

'''  def loss_function(self,y_pred,y):
    E=1e-7
    y_pred=torch.clamp(y_pred,E,1-E)

    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss'''

'  def loss_function(self,y_pred,y):\n    E=1e-7\n    y_pred=torch.clamp(y_pred,E,1-E)\n\n    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()\n    return loss'

**Important parameters**

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
#built-in loss fn
loss_function=nn.BCELoss()

**Training pipeline**

In [ ]:
# Ensure all tensors are double precision
X_train_tensor = torch.from_numpy(X_train).double()
X_test_tensor = torch.from_numpy(X_test).double()
y_train_tensor = torch.from_numpy(y_train).double()
y_test_tensor = torch.from_numpy(y_test).double()

#Create model
model = Model(X_train_tensor.shape[1])
model.double() # Cast the model's parameters to double precision


# Built-in optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Training loop
# Define loop
for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:

    # Forward pass
    y_pred = model(X_train_tensor)

    # Loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # Backward pass
    loss.backward()

    # Parameters update using optimizer
    optimizer.step()
    optimizer.zero_grad()  #manually zero gradients

    print(f'epoch:{epoch+1},Loss:{loss.item()}')

epoch:1,Loss:0.819505852445447
epoch:1,Loss:0.7994291736288485
epoch:1,Loss:0.7844295162386061
epoch:1,Loss:0.7721423242707695
epoch:1,Loss:0.7612916958767193
epoch:1,Loss:0.7510501348933468
epoch:1,Loss:0.7414698984609841
epoch:1,Loss:0.7321481749522426
epoch:1,Loss:0.7226411272724479
epoch:1,Loss:0.7129106824831613
epoch:1,Loss:0.702791963434851
epoch:1,Loss:0.6922314105710768
epoch:1,Loss:0.6816100924942989
epoch:1,Loss:0.6707718875213516
epoch:1,Loss:0.6597648968804866
epoch:1,Loss:0.6486854097937762
epoch:1,Loss:0.6376631559739475
epoch:1,Loss:0.6267699790697272
epoch:1,Loss:0.6159926081418785
epoch:1,Loss:0.6053946136069549
epoch:1,Loss:0.5949726644376532
epoch:1,Loss:0.5847054618138182
epoch:1,Loss:0.5746395079026261
epoch:1,Loss:0.5647809934400889
epoch:1,Loss:0.5551916343027038
epoch:1,Loss:0.5458681148737943
epoch:1,Loss:0.5367826094642677
epoch:1,Loss:0.5279221244140394
epoch:1,Loss:0.5192480080416764
epoch:2,Loss:0.5107805878514827
epoch:2,Loss:0.5025344668764796
epoch:2,Loss:0.49450511477233483
epoch:2,Loss:0.4866667776934774
epoch:2,Loss:0.47903201121589956
epoch:2,Loss:0.4716079787548676
epoch:2,Loss:0.46438202404662654
epoch:2,Loss:0.4573444022932519
epoch:2,Loss:0.45049082405070817
epoch:2,Loss:0.4438188105118218
epoch:2,Loss:0.43731485594292907
epoch:2,Loss:0.4309798430719656
epoch:2,Loss:0.4248083172573328
epoch:2,Loss:0.41879181022325146
epoch:2,Loss:0.41293201966094395
epoch:2,Loss:0.4072252948890765
epoch:2,Loss:0.40166442204995473
epoch:2,Loss:0.3962420826952402
epoch:2,Loss:0.3909560734156164
epoch:2,Loss:0.38579371496611053
epoch:2,Loss:0.3807602639143635
epoch:2,Loss:0.37585126419425446
epoch:2,Loss:0.37107647063979304
epoch:2,Loss:0.3664157569626097
epoch:2,Loss:0.36186384882480677
epoch:2,Loss:0.3574173946387055
epoch:2,Loss:0.35307487443357566
epoch:2,Loss:0.3488319932022348
epoch:2,Loss:0.3446799450355329
epoch:3,Loss:0.3406247853065059
epoch:3,Loss:0.3366622732301385
epoch:3,Loss:0.3327869208639879
epoch:3,Loss:0.32898419472438595
epoch:3,Loss:0.32526158614877065
epoch:3,Loss:0.3216157835329801
epoch:3,Loss:0.31804888881747995
epoch:3,Loss:0.3145586082805266
epoch:3,Loss:0.3111439518386683
epoch:3,Loss:0.307803867124769
epoch:3,Loss:0.30452776053899633
epoch:3,Loss:0.3013198135523272
epoch:3,Loss:0.29817837093174876
epoch:3,Loss:0.2951029153597632
epoch:3,Loss:0.2920908210671036
epoch:3,Loss:0.2891396854429525
epoch:3,Loss:0.28624759818152035
epoch:3,Loss:0.2834134210784176
epoch:3,Loss:0.2806352173275834
epoch:3,Loss:0.2779101728810754
epoch:3,Loss:0.27523397550567846
epoch:3,Loss:0.2726094154729999
epoch:3,Loss:0.27003535587885763
epoch:3,Loss:0.26751024944161056
epoch:3,Loss:0.2650331395541984
epoch:3,Loss:0.26259702514772776
epoch:3,Loss:0.2601958775574764
epoch:3,Loss:0.2578409383163741
epoch:3,Loss:0.2555285237807747
epoch:4,Loss:0.2532582159460176
epoch:4,Loss:0.25103585868124356
epoch:4,Loss:0.2488598041338241
epoch:4,Loss:0.24672361755544517
epoch:4,Loss:0.24462586982203421
epoch:4,Loss:0.24256444363598983
epoch:4,Loss:0.2405412153721607
epoch:4,Loss:0.2385501890510648
epoch:4,Loss:0.23658637227870843
epoch:4,Loss:0.2346562140779532
epoch:4,Loss:0.2327576373710912
epoch:4,Loss:0.23089170958055852
epoch:4,Loss:0.22905545728815851
epoch:4,Loss:0.2272506927994238
epoch:4,Loss:0.22547629454379992
epoch:4,Loss:0.22373451918465104
epoch:4,Loss:0.22201721736702182
epoch:4,Loss:0.2203133172669226
epoch:4,Loss:0.21863610196556357
epoch:4,Loss:0.21698498581079612
epoch:4,Loss:0.21535940011423327
epoch:4,Loss:0.21375879253923058
epoch:4,Loss:0.21218262651444586
epoch:4,Loss:0.21063038067179485
epoch:4,Loss:0.20910158396862244
epoch:4,Loss:0.20759580197318334
epoch:4,Loss:0.2061123467897164
epoch:4,Loss:0.20465297170362196
epoch:4,Loss:0.20321785418061514
epoch:5,Loss:0.20180443938709336
epoch:5,Loss:0.20041313595237678
epoch:5,Loss:0.19904215224730532
epoch:5,Loss:0.19769095691840555
epoch:5,Loss:0.19635915196712753
epoch:5,Loss:0.19504634991083497
epoch:5,Loss:0.19375286135843534
epoch:5,Loss:0.1924779636854384
epoch:5,Loss:0.1912209553020811
epoch:5,Loss:0.1899814852661474
epoch:5,Loss:0.1887592117497282
epoch:5,Loss:0.18755380173373637
epoch:5,Loss:0.1863650164297212
epoch:5,Loss:0.18519239501756157
epoch:5,Loss:0.18403565638936442
epoch:5,Loss:0.18289532863451527
epoch:5,Loss:0.18177105758323545
epoch:5,Loss:0.18065499721338762
epoch:5,Loss:0.17955357096577468
epoch:5,Loss:0.1784665129000539
epoch:5,Loss:0.17739356333145123
epoch:5,Loss:0.1763344686405036
epoch:5,Loss:0.17528898108993307
epoch:5,Loss:0.17425699664073754
epoch:5,Loss:0.17324020459444026
epoch:5,Loss:0.1722387283364154
epoch:5,Loss:0.17125004167727842
epoch:5,Loss:0.17027376220328336
epoch:5,Loss:0.1693096733185628
epoch:6,Loss:0.16835756329545293
epoch:6,Loss:0.16741722513256627
epoch:6,Loss:0.16648845641809473
epoch:6,Loss:0.1655710591981201
epoch:6,Loss:0.16466494410558924
epoch:6,Loss:0.16377024652954988
epoch:6,Loss:0.16288643780557469
epoch:6,Loss:0.1620131655150921
epoch:6,Loss:0.1611503215677178
epoch:6,Loss:0.16029773993996527
epoch:6,Loss:0.15945525052425386
epoch:6,Loss:0.15862268678546176
epoch:6,Loss:0.15779988566518574
epoch:6,Loss:0.15698704383970166
epoch:6,Loss:0.15618491788247918
epoch:6,Loss:0.15539216917381649
epoch:6,Loss:0.1546084108770313
epoch:6,Loss:0.15383361909752694
epoch:6,Loss:0.1530676503693929
epoch:6,Loss:0.15231036412014062
epoch:6,Loss:0.15156162259639766
epoch:6,Loss:0.1508213671771842
epoch:6,Loss:0.15008974057110802
epoch:6,Loss:0.14936804854843805
epoch:6,Loss:0.14865435185086867
epoch:6,Loss:0.14794859322338014
epoch:6,Loss:0.14725071717825808
epoch:6,Loss:0.1465602726300043
epoch:6,Loss:0.14587733787933266
epoch:7,Loss:0.14520201672360694
epoch:7,Loss:0.1445338194040995
epoch:7,Loss:0.14387277395403403
epoch:7,Loss:0.14321904961558232
epoch:7,Loss:0.1425722034018204
epoch:7,Loss:0.14193210575705925
epoch:7,Loss:0.14129906389917002
epoch:7,Loss:0.1406723696862053
epoch:7,Loss:0.1400524585641384
epoch:7,Loss:0.1394392452919231
epoch:7,Loss:0.1388325611401472
epoch:7,Loss:0.13823225190975583
epoch:7,Loss:0.13763805179406052
epoch:7,Loss:0.13704998829130513
epoch:7,Loss:0.13646842588326374
epoch:7,Loss:0.1358924803272084
epoch:7,Loss:0.13531304906313013
epoch:7,Loss:0.13473952819444768
epoch:7,Loss:0.13417193601290256
epoch:7,Loss:0.13360991453060808
epoch:7,Loss:0.13305352394218403
epoch:7,Loss:0.13250307851791618
epoch:7,Loss:0.1319586882984372
epoch:7,Loss:0.13142073445288766
epoch:7,Loss:0.13088981688857268
epoch:7,Loss:0.13036531241283267
epoch:7,Loss:0.12984596633926707
epoch:7,Loss:0.129331659023633
epoch:7,Loss:0.12882231909851266
epoch:8,Loss:0.128317876458163
epoch:8,Loss:0.1278182622326269
epoch:8,Loss:0.12732360578582785
epoch:8,Loss:0.126834898512971
epoch:8,Loss:0.12635081069477708
epoch:8,Loss:0.1258712781903444
epoch:8,Loss:0.12539623797755933
epoch:8,Loss:0.12492562813040876
epoch:8,Loss:0.12445938779682778
epoch:8,Loss:0.12399745717706702
epoch:8,Loss:0.12353943327391802
epoch:8,Loss:0.123081497159394
epoch:8,Loss:0.12262855989577194
epoch:8,Loss:0.1221798147132751
epoch:8,Loss:0.12173520384989839
epoch:8,Loss:0.12129467058089319
epoch:8,Loss:0.12085815919583179
epoch:8,Loss:0.1204256354185309
epoch:8,Loss:0.1199975763827719
epoch:8,Loss:0.11957336598498154
epoch:8,Loss:0.11915295259942474
epoch:8,Loss:0.11873628550411951
epoch:8,Loss:0.11832331486143903
epoch:8,Loss:0.11791399169922577
epoch:8,Loss:0.1175082678924012
epoch:8,Loss:0.11710609614505549
epoch:8,Loss:0.11670784222467397
epoch:8,Loss:0.11631368215780896
epoch:8,Loss:0.11592290743121532
epoch:9,Loss:0.11553547482140633
epoch:9,Loss:0.11515134181412107
epoch:9,Loss:0.11477046659069921
epoch:9,Loss:0.11439280801475611
epoch:9,Loss:0.11401832561914911
epoch:9,Loss:0.11364697959322871
epoch:9,Loss:0.11327873077036613
epoch:9,Loss:0.1129135406157515
epoch:9,Loss:0.11255137121445491
epoch:9,Loss:0.11219218525974398
epoch:9,Loss:0.11183594604165176
epoch:9,Loss:0.1114829280654155
epoch:9,Loss:0.11113373208738554
epoch:9,Loss:0.1107873802783959
epoch:9,Loss:0.11044383806672022
epoch:9,Loss:0.11010337479435317
epoch:9,Loss:0.10976604606710279
epoch:9,Loss:0.10943141239327142
epoch:9,Loss:0.10909944152123997
epoch:9,Loss:0.10877010169795678
epoch:9,Loss:0.10844336165993095
epoch:9,Loss:0.10811919062441556
epoch:9,Loss:0.10779755828077663
epoch:9,Loss:0.10747843478204162
epoch:9,Loss:0.10716179073662299
epoch:9,Loss:0.10684759720021172
epoch:9,Loss:0.10653582566783709
epoch:9,Loss:0.10622644806608687
epoch:9,Loss:0.10591943674548504
epoch:10,Loss:0.10561476447302268
epoch:10,Loss:0.10531240442483747
epoch:10,Loss:0.10501270288960432
epoch:10,Loss:0.10471599066425624
epoch:10,Loss:0.10442151238720282
epoch:10,Loss:0.10412924240448658
epoch:10,Loss:0.10383915545571185
epoch:10,Loss:0.10355122666650105
epoch:10,Loss:0.10326543154114717
epoch:10,Loss:0.10298174595545473
epoch:10,Loss:0.10270014614976154
epoch:10,Loss:0.10242060872213381
epoch:10,Loss:0.10214311062172858
epoch:10,Loss:0.10186762914231658
epoch:10,Loss:0.10159414191595983
epoch:10,Loss:0.10132262690683828
epoch:10,Loss:0.10105306240522034
epoch:10,Loss:0.10078542702157194
epoch:10,Loss:0.10051969968079974
epoch:10,Loss:0.1002558596166239
epoch:10,Loss:0.09999388636607551
epoch:10,Loss:0.09973375976411576
epoch:10,Loss:0.09947545993837209
epoch:10,Loss:0.09921896730398773
epoch:10,Loss:0.09896455652562991
epoch:10,Loss:0.09871223770933281
epoch:10,Loss:0.09846167143752062
epoch:10,Loss:0.09821283907323218
epoch:10,Loss:0.09796572224759359
epoch:11,Loss:0.09772030285508163
epoch:11,Loss:0.09747656304889106
epoch:11,Loss:0.09723448523640314
epoch:11,Loss:0.09699405207475151
epoch:11,Loss:0.09675524646648279
epoch:11,Loss:0.0965180515553089
epoch:11,Loss:0.09628245072194881
epoch:11,Loss:0.09604842758005593
epoch:11,Loss:0.09581596597223037
epoch:11,Loss:0.09558504996611195
epoch:11,Loss:0.09535566385055326
epoch:11,Loss:0.09512779213186918
epoch:11,Loss:0.09490141953016196
epoch:11,Loss:0.094676530975719
epoch:11,Loss:0.09445311160548214
epoch:11,Loss:0.09423114675958578
epoch:11,Loss:0.09401062197796319
epoch:11,Loss:0.09379152299701791
epoch:11,Loss:0.09357383574636012
epoch:11,Loss:0.09335754634560525
epoch:11,Loss:0.0931426411012337
epoch:11,Loss:0.0929291065035106
epoch:11,Loss:0.09271692922346349
epoch:11,Loss:0.09250609610991715
epoch:11,Loss:0.09229659418658409
epoch:11,Loss:0.09208841064920913
epoch:11,Loss:0.09188153286276741
epoch:11,Loss:0.09167594835871433
epoch:11,Loss:0.09147164483228597
epoch:12,Loss:0.09126861013984967
epoch:12,Loss:0.09106683229630282
epoch:12,Loss:0.09086629947251951
epoch:12,Loss:0.09066699999284364
epoch:12,Loss:0.09046892233262739
epoch:12,Loss:0.09027205511581474
epoch:12,Loss:0.09007638711256834
epoch:12,Loss:0.08988190723693923
epoch:12,Loss:0.08968870687492254
epoch:12,Loss:0.08949695245157326
epoch:12,Loss:0.08930643688035228
epoch:12,Loss:0.08911732639936779
epoch:12,Loss:0.08892935268445461
epoch:12,Loss:0.08874250530914161
epoch:12,Loss:0.08855677398020949
epoch:12,Loss:0.08837214853555922
epoch:12,Loss:0.08818861894211924
epoch:12,Loss:0.08800617529378925
epoch:12,Loss:0.08782480780942127
epoch:12,Loss:0.0876445068308364
epoch:12,Loss:0.08746529399978142
epoch:12,Loss:0.08728719785783548
epoch:12,Loss:0.08711013733819652
epoch:12,Loss:0.08693410327865089
epoch:12,Loss:0.08675908663133823
epoch:12,Loss:0.08658507846085736
epoch:12,Loss:0.08641208521867903
epoch:12,Loss:0.08624007316212914
epoch:12,Loss:0.08606903761508784
epoch:13,Loss:0.08589897593431652
epoch:13,Loss:0.08572987971657656
epoch:13,Loss:0.08556174066076727
epoch:13,Loss:0.08539455056628002
epoch:13,Loss:0.08522830133138691
epoch:13,Loss:0.0850629849516626
epoch:13,Loss:0.0848985935184388
epoch:13,Loss:0.08473511921728938
epoch:13,Loss:0.08457265519615297
epoch:13,Loss:0.08441119221474563
epoch:13,Loss:0.0842506227881586
epoch:13,Loss:0.08409099778860048
epoch:13,Loss:0.08393219426797095
epoch:13,Loss:0.0837742605067182
epoch:13,Loss:0.08361719099631619
epoch:13,Loss:0.08346097860990452
epoch:13,Loss:0.08330562453940414
epoch:13,Loss:0.08315115586134215
epoch:13,Loss:0.08299747244375663
epoch:13,Loss:0.08284461850004245
epoch:13,Loss:0.08269258730265754
epoch:13,Loss:0.08254137220094644
epoch:13,Loss:0.08239098629647545
epoch:13,Loss:0.08224142186338293
epoch:13,Loss:0.0820926155155144
epoch:13,Loss:0.08194459944038748
epoch:13,Loss:0.08179736735191578
epoch:13,Loss:0.08165091303424511
epoch:13,Loss:0.08150526415963134
epoch:14,Loss:0.08136037028444341
epoch:14,Loss:0.08121621235823102
epoch:14,Loss:0.08107280805021874
epoch:14,Loss:0.08093015147800728
epoch:14,Loss:0.08078823682347018
epoch:14,Loss:0.08064710997153449
epoch:14,Loss:0.08050669207260813
epoch:14,Loss:0.08036701478897212
epoch:14,Loss:0.08022806759774025
epoch:14,Loss:0.08008992004310236
epoch:14,Loss:0.07995238149232056
epoch:14,Loss:0.07981557027481875
epoch:14,Loss:0.07967951414668331
epoch:14,Loss:0.07954406588349602
epoch:14,Loss:0.07940934262551527
epoch:14,Loss:0.07927533069335689
epoch:14,Loss:0.07914192579538452
epoch:14,Loss:0.07900924421774898
epoch:14,Loss:0.07887723048335431
epoch:14,Loss:0.07874582348497651
epoch:14,Loss:0.0786151389476545
epoch:14,Loss:0.07848507861396398
epoch:14,Loss:0.07835562544410452
epoch:14,Loss:0.07822689485757736
epoch:14,Loss:0.078098744297611
epoch:14,Loss:0.07797120222109738
epoch:14,Loss:0.07784438396429501
epoch:14,Loss:0.07771810069024727
epoch:14,Loss:0.07759243727948209
epoch:15,Loss:0.07746747332893093
epoch:15,Loss:0.07734302464951319
epoch:15,Loss:0.07721920894721818
epoch:15,Loss:0.07709604226092552
epoch:15,Loss:0.07697339686390658
epoch:15,Loss:0.07685139069952052
epoch:15,Loss:0.07672998177972153
epoch:15,Loss:0.07660910137254556
epoch:15,Loss:0.07648886780029407
epoch:15,Loss:0.07636917816882856
epoch:15,Loss:0.07625002556154388
epoch:15,Loss:0.07613152880087365
epoch:15,Loss:0.07601352097087585
epoch:15,Loss:0.07589606998435405
epoch:15,Loss:0.0757792557536983
epoch:15,Loss:0.07566290282141129
epoch:15,Loss:0.07554713303348726
epoch:15,Loss:0.07543193868953728
epoch:15,Loss:0.07531721947642668
epoch:15,Loss:0.0752030978506792
epoch:15,Loss:0.07508948851270904
epoch:15,Loss:0.07497639315522968
epoch:15,Loss:0.07486398982807707
epoch:15,Loss:0.07475203335142598
epoch:15,Loss:0.07464060023566259
epoch:15,Loss:0.07452974762840789
epoch:15,Loss:0.07441932399198957
epoch:15,Loss:0.0743094566081698
epoch:15,Loss:0.07420009668640774
epoch:16,Loss:0.07409118691646464
epoch:16,Loss:0.07398285598778809
epoch:16,Loss:0.07387495648123883
epoch:16,Loss:0.07376755671545017
epoch:16,Loss:0.07366077889832101
epoch:16,Loss:0.07355438510578755
epoch:16,Loss:0.07344858147377673
epoch:16,Loss:0.07334315516026402
epoch:16,Loss:0.07323827992856495
epoch:16,Loss:0.07313382434323319
epoch:16,Loss:0.07302986628723344
epoch:16,Loss:0.07292636759725062
epoch:16,Loss:0.0728233156745905
epoch:16,Loss:0.07272076030528701
epoch:16,Loss:0.07261860365249118
epoch:16,Loss:0.07251697828024252
epoch:16,Loss:0.07241570663917077
epoch:16,Loss:0.0723149971274767
epoch:16,Loss:0.07221461830444124
epoch:16,Loss:0.0721147761633962
epoch:16,Loss:0.07201529658218189
epoch:16,Loss:0.0719163116118027
epoch:16,Loss:0.07181771871113267
epoch:16,Loss:0.07171958087182066
epoch:16,Loss:0.07162186231695278
epoch:16,Loss:0.07152456172664047
epoch:16,Loss:0.07142770540338425
epoch:16,Loss:0.07133128608290931
epoch:16,Loss:0.07123547730464162
epoch:17,Loss:0.07114001908996408
epoch:17,Loss:0.07104504851452141
epoch:17,Loss:0.07095039749604097
epoch:17,Loss:0.07085625448632328
epoch:17,Loss:0.0707624082548907
epoch:17,Loss:0.07066906679793478
epoch:17,Loss:0.07057602832815614
epoch:17,Loss:0.07048346758519124
epoch:17,Loss:0.07039123208227212
epoch:17,Loss:0.07029944244528381
epoch:17,Loss:0.07020799970177603
epoch:17,Loss:0.07011697174912403
epoch:17,Loss:0.07002631169780857
epoch:17,Loss:0.06993603618839529
epoch:17,Loss:0.06984614890079521
epoch:17,Loss:0.06975661676850753
epoch:17,Loss:0.06966749245336434
epoch:17,Loss:0.06957869480177195
epoch:17,Loss:0.0694903238034904
epoch:17,Loss:0.06940225190078537
epoch:17,Loss:0.06931462469785186
epoch:17,Loss:0.06922726997201556
epoch:17,Loss:0.06914037717539426
epoch:17,Loss:0.06905373922035123
epoch:17,Loss:0.06896762615580389
epoch:17,Loss:0.06888186840994737
epoch:17,Loss:0.06879661923419683
epoch:17,Loss:0.06871185069957007
epoch:17,Loss:0.06862744435008236
epoch:18,Loss:0.06854324954371571
epoch:18,Loss:0.06845963768019163
epoch:18,Loss:0.06837580388514514
epoch:18,Loss:0.06828427614245071
epoch:18,Loss:0.06819311579371658
epoch:18,Loss:0.068102365616241
epoch:18,Loss:0.06801205325016212
epoch:18,Loss:0.06792216908888433
epoch:18,Loss:0.06783270720118974
epoch:18,Loss:0.06774355432650285
epoch:18,Loss:0.06765485006353485
epoch:18,Loss:0.06756644926582751
epoch:18,Loss:0.06747847503833677
epoch:18,Loss:0.06739103809463247
epoch:18,Loss:0.06730391289529217
epoch:18,Loss:0.06721719656100925
epoch:18,Loss:0.06713081759703543
epoch:18,Loss:0.0670447662571831
epoch:18,Loss:0.0669591134379781
epoch:18,Loss:0.06687395331538336
epoch:18,Loss:0.06678904756176293
epoch:18,Loss:0.06670455949024916
epoch:18,Loss:0.06662096908391475
epoch:18,Loss:0.06653762535545102
epoch:18,Loss:0.06645462745248805
epoch:18,Loss:0.06637208920907899
epoch:18,Loss:0.06628977116786737
epoch:18,Loss:0.0662077727049762
epoch:18,Loss:0.0661261100412018
epoch:19,Loss:0.06604483975990635
epoch:19,Loss:0.06596384511090063
epoch:19,Loss:0.06588314004939193
epoch:19,Loss:0.06580275423115987
epoch:19,Loss:0.06572269588021337
epoch:19,Loss:0.0656429749108117
epoch:19,Loss:0.0655635238173257
epoch:19,Loss:0.06548439777278171
epoch:19,Loss:0.06540555180442163
epoch:19,Loss:0.06532700815808336
epoch:19,Loss:0.06524876412635706
epoch:19,Loss:0.06517082711382152
epoch:19,Loss:0.06509319146243912
epoch:19,Loss:0.06501582479258543
epoch:19,Loss:0.06493874795792735
epoch:19,Loss:0.06486195854578501
epoch:19,Loss:0.06478546443102702
epoch:19,Loss:0.06470930201647439
epoch:19,Loss:0.06463274740359191
epoch:19,Loss:0.06455274424511917
epoch:19,Loss:0.06447310873265781
epoch:19,Loss:0.06439383517757767
epoch:19,Loss:0.06431497710410027
epoch:19,Loss:0.06423653640121131
epoch:19,Loss:0.06415844096575951
epoch:19,Loss:0.0640806960504731
epoch:19,Loss:0.06400329641463989
epoch:19,Loss:0.06392623702678824
epoch:19,Loss:0.06384951305381446
epoch:20,Loss:0.06377311985067234
epoch:20,Loss:0.06369705295059734
epoch:20,Loss:0.06362130805584046
epoch:20,Loss:0.06354588102888628
epoch:20,Loss:0.06347076788413229
epoch:20,Loss:0.06339596478000653
epoch:20,Loss:0.06332146801150206
epoch:20,Loss:0.06324727400310723
epoch:20,Loss:0.06317337930211271
epoch:20,Loss:0.06309978057227543
epoch:20,Loss:0.06302647458782229
epoch:20,Loss:0.06295374136947977
epoch:20,Loss:0.06288179477777896
epoch:20,Loss:0.06281012283900737
epoch:20,Loss:0.0627388648116926
epoch:20,Loss:0.06266819852652537
epoch:20,Loss:0.06259751827429325
epoch:20,Loss:0.0625273698140166
epoch:20,Loss:0.062457276060321205
epoch:20,Loss:0.06238761460176179
epoch:20,Loss:0.06231813223106558
epoch:20,Loss:0.062248963729517146
epoch:20,Loss:0.062180096846570006
epoch:20,Loss:0.062111370962311195
epoch:20,Loss:0.06204310302193655
epoch:20,Loss:0.06197479422663167
epoch:20,Loss:0.061907131868459885
epoch:20,Loss:0.061839248701551504
epoch:20,Loss:0.06177236102761511
epoch:21,Loss:0.06170556450925481
epoch:21,Loss:0.06163935585258383
epoch:21,Loss:0.06157316916271964
epoch:21,Loss:0.06150728700011319
epoch:21,Loss:0.0614417126169462
epoch:21,Loss:0.06137614142147886
epoch:21,Loss:0.06131118139483405
epoch:21,Loss:0.06124598818295077
epoch:21,Loss:0.061181482543495466
epoch:21,Loss:0.06111682546907541
epoch:21,Loss:0.06105259198058198
epoch:21,Loss:0.06098855577768335
epoch:21,Loss:0.06092458196735822
epoch:21,Loss:0.06086116719712453
epoch:21,Loss:0.060797531207925935
epoch:21,Loss:0.060734559474990804
epoch:21,Loss:0.060671446635386185
epoch:21,Loss:0.0606087024884164
epoch:21,Loss:0.060546214380134744
epoch:21,Loss:0.06048368781165233

In [ ]:
model.bias

tensor([-0.1602], dtype=torch.float64, requires_grad=True)

**Evaluation**

In [ ]:
model.eval()
accuracy_list=[]
with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred=model.forward(batch_features)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==batch_labels.view(-1,1)).float().mean()
    accuracy_list.append(accuracy.item())
    overall_accuracy=sum(accuracy_list)/len(accuracy_list)
    print(f'Accuracy:{overall_accuracy:.4f}')
''''with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()}')'''

Accuracy:1.0000
Accuracy:0.9688
Accuracy:0.9792
Accuracy:0.9844
Accuracy:0.9875
Accuracy:0.9896
Accuracy:0.9732
Accuracy:0.9766

"'with torch.no_grad():\n  y_pred=model.forward(X_test_tensor)\n  y_pred=(y_pred>0.5).float()\n  accuracy=(y_pred==y_test_tensor).float().mean()\n  print(f'Accuracy:{accuracy.item()}')"